version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - "3001:3001"
    networks:
      - api
    volumes:
      - '.:/project'

  db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    volumes:
      - .db/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports: 
      - "5432:5432"
    networks:
      - api
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - api

networks:
  api:
    driver: bridge