version: '3.8'
services:
  nginx:
    container_name: reverse
    build: ./nginx
    ports:
      - 3000:80
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - "3001:3001"
    networks:
      - api
    volumes:
      - '.:/project'

  db:
    container_name: pg_container
    image: postgres:15-alpine
    restart: always
    volumes:
      - .db/postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      - api
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  data: {}